version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: m347-kn04a-db
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: testdb
    networks:
      custom_net:
        ipv4_address: 172.10.5.10

  web:
    build: .
    container_name: m347-kn04a-web
    depends_on:
      - db
    ports:
      - "8085:80"
    networks:
      custom_net:
        ipv4_address: 172.10.5.11

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          ip_range: 172.10.5.0/24
          gateway: 172.10.5.254
